apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shopper
  name: shopper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopper
  template:
    metadata:
      labels:
        app: shopper
    spec:
      containers:
      - image: 437928576289.dkr.ecr.ap-south-1.amazonaws.com/shopper-frontend:latest
        name: shopper
        ports:
        - containerPort: 80
          name: shopper
